efm:
  base-url: https://california-efm-stage.tylertech.cloud
  user-service:
    wsdl-location: classpath:wsdlprod/EfmUserService.wsdl
    endpoint-url: ${efm.base-url}/EFM/EFMUserService.svc
  court-record-service:
    wsdl-location: classpath:wsdlprod/CourtRecordMDEService.wsdl
    endpoint-url: ${efm.base-url}/EFM/CourtRecordMDEService.svc
  firm-service:
    wsdl-location: classpath:wsdlprod/EFMFirmService.wsdl
    endpoint-url: ${efm.base-url}/EFM/EFMFirmService.svc
